name: Postman API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r services/webhook_receiver/requirements.txt

      - name: Start Flask server
        run: |
          python services/webhook_receiver/app.py &
          sleep 2

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run Postman collection
        run: |
          postman collection run "postman/Fintech Integration Starter Kit.postman_collection.json" \
            --environment postman/local.postman_environment.json